In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sys
sys.path.append("/Users/yohei.moriya/src/")
import rakus_ml_training as rmt

/Users/yohei.moriya/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/yohei.moriya/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/yohei.moriya/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/yohei.moriya/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


load success rakus_ml_training


In [ ]:
def softmax(nd_x: pd.DataFrame):
    """
    ソフトマックス関数に入力した値を計算します。

    :param nd_x:
    :return:
    """
    return np.exp(nd_x) / np.sum(np.exp(nd_x))

df = pd.DataFrame([10, 20, 30])

df_s = softmax(df.values)
print(df_s)
print(df_s.sum())


In [ ]:
def onehot_to_flat(df_hot: pd.DataFrame):
    """
    one-hot で表現されているを１次元のデータに圧縮します。
    :return:
    """
    
    return 
    
    
df = pd.DataFrame([0,0,3,0,1,1,3,1,2])
df.values.flatten()
df_1hot = pd.get_dummies(df.values.flatten())
display(df_1hot)
# onehot_to_flat(df_1hot)

df_1hot.max()
df_1hot.idxmax(axis=1)

df = df_1hot.idxmax(axis=1)
df.columns = ['target']
display(df)

In [ ]:
nd_a = np.random.random((5,3))
df_a = pd.DataFrame(nd_a)
display(df_a)
nd_b = np.random.random((5,9))
df_b = pd.DataFrame(nd_b)
display(df_b)

ans = df_b.mul(df_a, axis=1)
ans = df_b.applymap(lambda s: s * df_a)

display(ans)

In [ ]:
df = rmt.iris.get_train_data()
df = norm(df)
for col in df.sort_values('target').drop('target', axis=1).columns:
    df.plot.scatter(x='target', y=col)

# df.plot(x='target', y=df.columns)

In [ ]:
def norm(df_origin):
    """
    行列を正規化します。
    """
    vec_mean = df_origin.mean()
    vec_var = df_origin.var()
    nd_train = df_origin.values
    nd_norm = (nd_train - vec_mean.values) / np.sqrt(vec_var).values
    return pd.DataFrame(data=nd_norm, columns=df_origin.columns, index=df_origin.index)

df = norm(df)
df_new = pd.DataFrame()
df_new['sepal'] = df['sepal length (cm)'] * df['petal width (cm)']
df_new['petal'] = df['sepal width (cm)'] * df['petal length (cm)']
df_new['target'] = df['target']

for col in df_new.sort_values('target').drop('target', axis=1).columns:
    df_new.plot.scatter(x='target', y=col)

In [13]:
df_train_origin = rmt.iris.get_train_data()
display(df_train_origin.head())
# df_train_ = df_train_origin.values.apply_along_axis(lambda series: series / 2)
nd_train = np.apply_along_axis(lambda series: series / 2, 1, df_train_origin)
display(nd_train)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

array([[2.55, 1.75, 0.7 , 0.1 , 0.  ],
       [2.45, 1.5 , 0.7 , 0.1 , 0.  ],
       [2.35, 1.6 , 0.65, 0.1 , 0.  ],
       [2.3 , 1.55, 0.75, 0.1 , 0.  ],
       [2.5 , 1.8 , 0.7 , 0.1 , 0.  ],
       [2.3 , 1.7 , 0.7 , 0.15, 0.  ],
       [2.5 , 1.7 , 0.75, 0.1 , 0.  ],
       [2.2 , 1.45, 0.7 , 0.1 , 0.  ],
       [2.45, 1.55, 0.75, 0.05, 0.  ],
       [2.7 , 1.85, 0.75, 0.1 , 0.  ],
       [2.4 , 1.7 , 0.8 , 0.1 , 0.  ],
       [2.4 , 1.5 , 0.7 , 0.05, 0.  ],
       [2.15, 1.5 , 0.55, 0.05, 0.  ],
       [2.85, 2.2 , 0.75, 0.2 , 0.  ],
       [2.55, 1.75, 0.7 , 0.15, 0.  ],
       [2.85, 1.9 , 0.85, 0.15, 0.  ],
       [2.7 , 1.7 , 0.85, 0.1 , 0.  ],
       [2.55, 1.85, 0.75, 0.2 , 0.  ],
       [2.3 , 1.8 , 0.5 , 0.1 , 0.  ],
       [2.55, 1.65, 0.85, 0.25, 0.  ],
       [2.4 , 1.7 , 0.95, 0.1 , 0.  ],
       [2.5 , 1.5 , 0.8 , 0.1 , 0.  ],
       [2.5 , 1.7 , 0.8 , 0.2 , 0.  ],
       [2.6 , 1.75, 0.75, 0.1 , 0.  ],
       [2.6 , 1.7 , 0.7 , 0.1 , 0.  ],
       [2.4 , 1.55, 0.8 ,

In [116]:
a = np.zeros((5, 3)) + 1
b = np.zeros((5, 9)) + 2
# X,Y = np.meshgrid(a, b)

a_ = np.tile(a,(3))

print(a_.shape)

a_ *  b

(5, 9)


array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [132]:
a = np.zeros((120, 3)) + 1
b = np.zeros((120, 9)) + 2

a_ = a.reshape(3, 120, 1)
a_ = np.tile(a_,(9))
# a_ = a.reshape(5, 1, 3)
# a_ = np.tile(a_,(3))

# print(f"a: {a.shape} \n {a}")
# print(f"a_: {a_.shape} \n {a_}")

ans = a_ * b
print(ans.shape)
print(ans.reshape(120, 9))


(3, 120, 9)


ValueError: cannot reshape array of size 3240 into shape (120,9)

In [122]:
def hoge(a, b):
    a_ = a.reshape(a.shape[1], a.shape[0], 1)
    print(a_.shape)
    print(a_.shape, b.shape)
    print(a_ *  b)
    
a = np.random.random((5, 3))
b = np.random.random((5, 9))
hoge(a, b)

(3, 5, 1)
(3, 5, 1) (5, 9)
[[[0.14048772 0.26519139 0.19884566 0.04678123 0.28744037 0.48768258
   0.28646805 0.03496249 0.09241412]
  [0.51609163 0.17664161 0.0958083  0.24605588 0.26215638 0.1866679
   0.44696241 0.37859024 0.2292308 ]
  [0.3271024  0.17955957 0.26249196 0.41910434 0.29914584 0.27828214
   0.01103508 0.34544089 0.08652406]
  [0.10599075 0.28370579 0.08604944 0.31304221 0.38529323 0.38326737
   0.09009036 0.03870863 0.02475729]
  [0.10341412 0.17487969 0.1279203  0.03409516 0.08881696 0.1708615
   0.18287302 0.18949844 0.15394906]]

 [[0.16572421 0.31282901 0.23456528 0.05518477 0.33907469 0.5752874
   0.33792771 0.04124298 0.10901492]
  [0.73370564 0.2511239  0.1362066  0.34980723 0.37269664 0.26537785
   0.63542755 0.53822572 0.32588773]
  [0.4166021  0.22868953 0.33431336 0.53377704 0.38099625 0.35442395
   0.01405442 0.43995826 0.11019822]
  [0.11517206 0.30828141 0.09350336 0.34015906 0.41866872 0.41646737
   0.09789431 0.04206171 0.02690185]
  [0.27121215 0.4586

In [85]:
a = np.random.random((2, 3))
b = np.random.random((3, 2, 3))

print(a)
print(b)
print(a - b)

[[0.4360848  0.91701585 0.70460583]
 [0.84900317 0.98334627 0.7670556 ]]
[[[0.8659     0.30347059 0.90498169]
  [0.13543996 0.98590624 0.06707152]]

 [[0.52610041 0.28368946 0.80545839]
  [0.17457622 0.40929568 0.4871083 ]]

 [[0.69149569 0.02407539 0.83113   ]
  [0.30797516 0.05961945 0.93526984]]]
[[[-0.42981519  0.61354527 -0.20037587]
  [ 0.71356321 -0.00255997  0.69998409]]

 [[-0.09001561  0.63332639 -0.10085256]
  [ 0.67442695  0.57405059  0.27994731]]

 [[-0.25541089  0.89294046 -0.12652417]
  [ 0.54102801  0.92372681 -0.16821423]]]
